"""Initial schema

Revision ID: 918f0ef7149f
Revises: 
Create Date: 2025-12-25 02:32:46.105926

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '918f0ef7149f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('supabase_id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('trading_start_date', sa.Date(), nullable=True),
    sa.Column('uc_enabled', sa.Boolean(), nullable=False),
    sa.Column('uc_assessment_day', sa.Integer(), nullable=True),
    sa.Column('tax_set_aside_percentage', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('stripe_customer_id', sa.String(), nullable=True),
    sa.Column('subscription_status', sa.String(), nullable=False),
    sa.Column('subscription_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_stripe_customer_id'), 'users', ['stripe_customer_id'], unique=True)
    op.create_index(op.f('ix_users_supabase_id'), 'users', ['supabase_id'], unique=True)
    op.create_table('expenses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('date_paid', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('tax_year', sa.String(length=7), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_expenses_date_paid'), 'expenses', ['date_paid'], unique=False)
    op.create_index(op.f('ix_expenses_tax_year'), 'expenses', ['tax_year'], unique=False)
    op.create_index(op.f('ix_expenses_user_id'), 'expenses', ['user_id'], unique=False)
    op.create_table('incomes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('date_received', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('tax_year', sa.String(length=7), nullable=False),
    sa.Column('tax_ruleset_version', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incomes_date_received'), 'incomes', ['date_received'], unique=False)
    op.create_index(op.f('ix_incomes_tax_year'), 'incomes', ['tax_year'], unique=False)
    op.create_index(op.f('ix_incomes_user_id'), 'incomes', ['user_id'], unique=False)
    op.create_table('tax_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('tax_year', sa.String(length=7), nullable=False),
    sa.Column('tax_year_start', sa.Date(), nullable=False),
    sa.Column('tax_year_end', sa.Date(), nullable=False),
    sa.Column('total_income', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_expenses', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('net_profit', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('income_tax', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('ni_class2', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('ni_class4', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_tax', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('tax_ruleset_version', sa.String(), nullable=False),
    sa.Column('ruleset_data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tax_snapshots_tax_year'), 'tax_snapshots', ['tax_year'], unique=False)
    op.create_index(op.f('ix_tax_snapshots_user_id'), 'tax_snapshots', ['user_id'], unique=False)
    op.create_table('uc_reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('total_income', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_expenses', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('net_profit', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('reported_at', sa.Date(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_uc_reports_period_start'), 'uc_reports', ['period_start'], unique=False)
    op.create_index(op.f('ix_uc_reports_user_id'), 'uc_reports', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_uc_reports_user_id'), table_name='uc_reports')
    op.drop_index(op.f('ix_uc_reports_period_start'), table_name='uc_reports')
    op.drop_table('uc_reports')
    op.drop_index(op.f('ix_tax_snapshots_user_id'), table_name='tax_snapshots')
    op.drop_index(op.f('ix_tax_snapshots_tax_year'), table_name='tax_snapshots')
    op.drop_table('tax_snapshots')
    op.drop_index(op.f('ix_incomes_user_id'), table_name='incomes')
    op.drop_index(op.f('ix_incomes_tax_year'), table_name='incomes')
    op.drop_index(op.f('ix_incomes_date_received'), table_name='incomes')
    op.drop_table('incomes')
    op.drop_index(op.f('ix_expenses_user_id'), table_name='expenses')
    op.drop_index(op.f('ix_expenses_tax_year'), table_name='expenses')
    op.drop_index(op.f('ix_expenses_date_paid'), table_name='expenses')
    op.drop_table('expenses')
    op.drop_index(op.f('ix_users_supabase_id'), table_name='users')
    op.drop_index(op.f('ix_users_stripe_customer_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
